"""Curated recipe & garnish seed data for The Mobile Mixery."""

IMG_LAVENDER = "https://images.unsplash.com/photo-1589378938275-947b7adf8665?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA3MDR8MHwxfHNlYXJjaHwxfHxsYXZlbmRlciUyMGNvY2t0YWlsJTIwcHVycGxlJTIwZHJpbmt8ZW58MHx8fHwxNzg4OTQwMjUyfDA&ixlib=rb-4.1.0&q=85"
IMG_FLORAL = "https://images.unsplash.com/photo-1582269438702-578efa319292?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA3MDR8MHwxfHNlYXJjaHwyfHxsYXZlbmRlciUyMGNvY2t0YWlsJTIwcHVycGxlJTIwZHJpbmt8ZW58MHx8fHwxNzg4OTQwMjUzfDA&ixlib=rb-4.1.0&q=85"
IMG_MINT = "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2MDV8MHwxfHNlYXJjaHwxfHxjb2NrdGFpbCUyMGdhcm5pc2glMjBmcmVzaCUyMGxpbWUlMjBtaW50fGVufDB8fHx8MTc4ODk0MDI1M3ww&ixlib=rb-4.1.0&q=85"
IMG_GRID = "https://images.unsplash.com/photo-1623593688280-a5aec8ac4ae7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2MDV8MHwxfHNlYXJjaHwyfHxjb2NrdGFpbCUyMGdhcm5pc2glMjBmcmVzaCUyMGxpbWUlMjBtaW50fGVufDB8fHx8MTc4ODk0MDI1M3ww&ixlib=rb-4.1.0&q=85"
IMG_HERO = "https://images.unsplash.com/photo-1621109328469-0e7c5f0c3fc7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNTl8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBiYXJ0ZW5kZXIlMjBwb3VyaW5nJTIwZHJpbmslMjBldmVudHxlbnwwfHx8fDE3ODg5NDAyNTN8MA&ixlib=rb-4.1.0&q=85"


def _r(id, name, category, tags, description, image_url, glass, spirit, ingredients, steps, garnish, difficulty="Easy"):
    return {
        "id": id,
        "name": name,
        "category": category,
        "tags": tags,
        "description": description,
        "image_url": image_url,
        "glass": glass,
        "base_spirit": spirit,
        "ingredients": ingredients,
        "steps": steps,
        "garnish": garnish,
        "difficulty": difficulty,
    }


SEED_RECIPES = [
    _r("lavender-haze", "Lavender Haze", "Cocktails", ["Floral", "Refreshing", "Signature"],
       "Our signature gin sour with house lavender syrup and a whisper of citrus.",
       IMG_LAVENDER, "Coupe", "Gin",
       ["2 oz gin", "0.75 oz lavender syrup", "0.75 oz fresh lemon juice", "1 egg white", "2 dashes lavender bitters"],
       ["Dry shake all ingredients without ice to build foam.", "Add ice and shake hard for 12 seconds.",
        "Double strain into a chilled coupe.", "Finish with lavender bitters on the foam."],
       "Dried lavender sprig & lemon twist", "Medium"),
    _r("purple-rain-spritz", "Purple Rain Spritz", "Cocktails", ["Bubbly", "Sweet", "Crowd Pleaser"],
       "A photogenic sparkling spritz with butterfly pea and prosecco.",
       IMG_FLORAL, "Wine Glass", "Prosecco",
       ["1 oz butterfly pea gin", "0.5 oz elderflower liqueur", "3 oz prosecco", "1 oz soda", "Squeeze of lemon"],
       ["Build gin and elderflower over ice.", "Top with prosecco and soda.", "Squeeze lemon and stir gently."],
       "Edible flower & lemon wheel"),
    _r("garden-mojito", "Garden Mojito", "Cocktails", ["Minty", "Refreshing", "Classic"],
       "A muddled mint and lime rum classic, endlessly refreshing for summer events.",
       IMG_MINT, "Highball", "White Rum",
       ["2 oz white rum", "1 oz fresh lime juice", "0.75 oz simple syrup", "8 mint leaves", "Soda water"],
       ["Muddle mint with syrup and lime.", "Add rum and ice, shake briefly.", "Strain over crushed ice, top with soda."],
       "Mint bouquet & lime wheel"),
    _r("citrus-paloma", "Citrus Paloma", "Cocktails", ["Citrus", "Tart", "Tequila"],
       "Bright tequila and grapefruit with a salted rim - a mobile-bar favorite.",
       IMG_GRID, "Highball", "Tequila",
       ["2 oz blanco tequila", "0.5 oz lime juice", "2 oz grapefruit soda", "Pinch of salt"],
       ["Salt the rim of a highball.", "Build tequila, lime and salt over ice.", "Top with grapefruit soda."],
       "Grapefruit wedge & rosemary"),
    _r("smoked-old-fashioned", "Smoked Old Fashioned", "Cocktails", ["Boozy", "Smoky", "Premium"],
       "A tableside smoked bourbon classic that wows guests at upscale events.",
       IMG_HERO, "Rocks", "Bourbon",
       ["2.5 oz bourbon", "0.25 oz demerara syrup", "2 dashes Angostura bitters", "Applewood smoke"],
       ["Stir bourbon, syrup and bitters with ice.", "Strain over a large cube.", "Cap the glass and fill with applewood smoke."],
       "Orange peel & brandied cherry", "Medium"),
    _r("french-75", "French 75", "Cocktails", ["Bubbly", "Elegant", "Classic"],
       "Champagne, gin and lemon - effervescent elegance for weddings.",
       IMG_FLORAL, "Flute", "Gin",
       ["1 oz gin", "0.5 oz lemon juice", "0.5 oz simple syrup", "3 oz champagne"],
       ["Shake gin, lemon and syrup with ice.", "Strain into a flute.", "Top with champagne."],
       "Long lemon twist"),
    _r("berry-basil-smash", "Berry Basil Smash", "Mocktails", ["Fruity", "Zero Proof", "Fresh"],
       "A vibrant zero-proof smash of muddled berries, basil and lime.",
       IMG_LAVENDER, "Rocks", "Zero-Proof",
       ["6 blackberries", "4 basil leaves", "0.75 oz lime juice", "0.5 oz simple syrup", "Soda water"],
       ["Muddle berries, basil, lime and syrup.", "Fill with crushed ice.", "Top with soda and swizzle."],
       "Skewered berries & basil"),
    _r("cucumber-cooler", "Cucumber Cooler", "Mocktails", ["Crisp", "Zero Proof", "Spa"],
       "Cool cucumber, mint and elderflower - a refreshing non-alcoholic sipper.",
       IMG_MINT, "Highball", "Zero-Proof",
       ["4 cucumber slices", "6 mint leaves", "0.5 oz elderflower cordial", "0.75 oz lime", "Tonic"],
       ["Muddle cucumber and mint.", "Add cordial and lime over ice.", "Top with tonic."],
       "Cucumber ribbon & mint"),
    _r("sparkling-pom", "Sparkling Pomegranate", "Mocktails", ["Sweet", "Zero Proof", "Festive"],
       "Festive pomegranate and citrus fizz that looks like a celebration.",
       IMG_FLORAL, "Coupe", "Zero-Proof",
       ["2 oz pomegranate juice", "0.5 oz lime", "0.5 oz honey syrup", "Sparkling water"],
       ["Shake juice, lime and honey syrup.", "Strain into a coupe.", "Top with sparkling water."],
       "Pomegranate arils & mint"),
    _r("rose-sangria", "Rosé Sangria", "Wine/Beer", ["Fruity", "Batch", "Summer"],
       "A batchable rosé sangria with stone fruit and berries - perfect for large crowds.",
       IMG_LAVENDER, "Wine Glass", "Rosé Wine",
       ["1 bottle rosé", "2 oz peach liqueur", "Sliced peaches", "Mixed berries", "Soda to top"],
       ["Combine rosé, liqueur and fruit.", "Chill for 2 hours.", "Serve over ice, top with soda."],
       "Fresh peach & berries"),
    _r("hoppy-shandy", "Citrus Hoppy Shandy", "Wine/Beer", ["Beer", "Citrus", "Casual"],
       "A crisp session ale lightened with fresh lemonade - a casual event staple.",
       IMG_GRID, "Pint", "Beer",
       ["6 oz session ale", "4 oz cloudy lemonade", "Squeeze of lemon"],
       ["Fill a pint half with chilled ale.", "Top with lemonade.", "Finish with a lemon squeeze."],
       "Lemon wheel"),
    _r("spiced-mule", "Spiced Ginger Mule", "Cocktails", ["Spicy", "Refreshing", "Classic"],
       "Vodka, fresh ginger beer and lime with a spicy kick, served in copper.",
       IMG_MINT, "Copper Mug", "Vodka",
       ["2 oz vodka", "0.5 oz lime juice", "4 oz ginger beer", "Candied ginger"],
       ["Build vodka and lime over ice in a copper mug.", "Top with ginger beer.", "Stir and garnish."],
       "Lime wedge & candied ginger"),
]

SEED_GARNISHES = [
    {"id": "g-citrus-twist", "title": "Expressed Citrus Twists", "image_url": IMG_GRID,
     "tip": "Express the oils over the drink, then perch the twist on the rim for aroma and shine."},
    {"id": "g-herb-bouquet", "title": "Fresh Herb Bouquets", "image_url": IMG_MINT,
     "tip": "Slap mint or basil to release oils and plant a generous bouquet for a fragrant, lush look."},
    {"id": "g-edible-flowers", "title": "Edible Flowers", "image_url": IMG_FLORAL,
     "tip": "Float pansies or a single lavender sprig for an elegant, photo-ready finish."},
    {"id": "g-dehydrated", "title": "Dehydrated Fruit Wheels", "image_url": IMG_LAVENDER,
     "tip": "Dehydrated citrus and berries add color, travel well, and never wilt on a mobile bar."},
    {"id": "g-skewers", "title": "Fruit & Berry Skewers", "image_url": IMG_GRID,
     "tip": "Skewer berries or brandied cherries for a playful bite guests love."},
    {"id": "g-rims", "title": "Flavored Rims", "image_url": IMG_HERO,
     "tip": "Rim with citrus salt, smoked sugar or crushed freeze-dried fruit for extra sensory impact."},
]
